name = "ai-digest-workflow"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]
main = "workers/index.ts"
assets = { directory = "./dist/" }

[[migrations]]
tag = "<v1>"
new_sqlite_classes = ["ChatToolsMcp"]

[durable_objects]
[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "ChatToolsMcp"

[observability]
enabled = true

[[workflows]]
name = "digest-workflow"
binding = "DIGEST_WORKFLOW"
class_name = "DigestWorkflow"
