name = "ai-digest-workflow"
compatibility_date = "2024-09-19"
main = "workers/index.ts"
assets = { directory = "./dist/" }

[observability]
enabled = true

[[workflows]]
name = "digest-workflow"
binding = "DIGEST_WORKFLOW"
class_name = "DigestWorkflow"
